create table Realm (realmId integer PRIMARY KEY, externalidentifier varchar(200));

insert into Realm (realmId, ExternalIdentifier) values (-1,'Aegwynn');
insert into Realm (realmId, ExternalIdentifier) values (-2,'AeriePeak');
insert into Realm (realmId, ExternalIdentifier) values (-3,'Agamaggan');
insert into Realm (realmId, ExternalIdentifier) values (-4,'Aggra(Português)');
insert into Realm (realmId, ExternalIdentifier) values (-5,'Aggramar');
insert into Realm (realmId, ExternalIdentifier) values (-6,'Ahn''Qiraj');
insert into Realm (realmId, ExternalIdentifier) values (-7,'Al''Akir');
insert into Realm (realmId, ExternalIdentifier) values (-8,'Alexstrasza');
insert into Realm (realmId, ExternalIdentifier) values (-9,'Alleria');
insert into Realm (realmId, ExternalIdentifier) values (-10,'Aerie Peak');
insert into Realm (realmId, ExternalIdentifier) values (-11,'Aggra (Português)');
insert into Realm (realmId, ExternalIdentifier) values (-12,'Alonsus');
insert into Realm (realmId, ExternalIdentifier) values (-13,'Aman''Thul');
insert into Realm (realmId, ExternalIdentifier) values (-14,'Ambossar');
insert into Realm (realmId, ExternalIdentifier) values (-15,'Anachronos');
insert into Realm (realmId, ExternalIdentifier) values (-16,'Anetheron');
insert into Realm (realmId, ExternalIdentifier) values (-17,'Antonidas');
insert into Realm (realmId, ExternalIdentifier) values (-18,'Anub''arak');
insert into Realm (realmId, ExternalIdentifier) values (-19,'Arak-arahm');
insert into Realm (realmId, ExternalIdentifier) values (-20,'Arathi');
insert into Realm (realmId, ExternalIdentifier) values (-21,'Arathor');
insert into Realm (realmId, ExternalIdentifier) values (-22,'Archimonde');
insert into Realm (realmId, ExternalIdentifier) values (-23,'Area 52');
insert into Realm (realmId, ExternalIdentifier) values (-24,'Argent Dawn');
insert into Realm (realmId, ExternalIdentifier) values (-25,'Arthas');
insert into Realm (realmId, ExternalIdentifier) values (-26,'Arygos');
insert into Realm (realmId, ExternalIdentifier) values (-27,'Ashenvale');
insert into Realm (realmId, ExternalIdentifier) values (-28,'Aszune');
insert into Realm (realmId, ExternalIdentifier) values (-29,'Auchindoun');
insert into Realm (realmId, ExternalIdentifier) values (-30,'Azjol-Nerub');
insert into Realm (realmId, ExternalIdentifier) values (-31,'Azshara');
insert into Realm (realmId, ExternalIdentifier) values (-32,'Azuregos');
insert into Realm (realmId, ExternalIdentifier) values (-33,'Azuremyst');
insert into Realm (realmId, ExternalIdentifier) values (-34,'Baelgun');
insert into Realm (realmId, ExternalIdentifier) values (-35,'Balnazzar');
insert into Realm (realmId, ExternalIdentifier) values (-36,'Blackhand');
insert into Realm (realmId, ExternalIdentifier) values (-37,'Blackmoore');
insert into Realm (realmId, ExternalIdentifier) values (-38,'Blackrock');
insert into Realm (realmId, ExternalIdentifier) values (-39,'Blackscar');
insert into Realm (realmId, ExternalIdentifier) values (-40,'Blade''s Edge');
insert into Realm (realmId, ExternalIdentifier) values (-41,'Bladefist');
insert into Realm (realmId, ExternalIdentifier) values (-42,'Bloodfeather');
insert into Realm (realmId, ExternalIdentifier) values (-43,'Bloodhoof');
insert into Realm (realmId, ExternalIdentifier) values (-44,'Bloodscalp');
insert into Realm (realmId, ExternalIdentifier) values (-45,'Blutkessel');
insert into Realm (realmId, ExternalIdentifier) values (-46,'Booty Bay');
insert into Realm (realmId, ExternalIdentifier) values (-47,'Borean Tundra');
insert into Realm (realmId, ExternalIdentifier) values (-48,'Boulderfist');
insert into Realm (realmId, ExternalIdentifier) values (-49,'Bronze Dragonflight');
insert into Realm (realmId, ExternalIdentifier) values (-50,'Bronzebeard');
insert into Realm (realmId, ExternalIdentifier) values (-51,'Burning Blade');
insert into Realm (realmId, ExternalIdentifier) values (-52,'Burning Steppes');
insert into Realm (realmId, ExternalIdentifier) values (-53,'C''Thun');
insert into Realm (realmId, ExternalIdentifier) values (-54,'Chamber of Aspects');
insert into Realm (realmId, ExternalIdentifier) values (-55,'Chants éternels');
insert into Realm (realmId, ExternalIdentifier) values (-56,'Cho''gall');
insert into Realm (realmId, ExternalIdentifier) values (-57,'Chromaggus');
insert into Realm (realmId, ExternalIdentifier) values (-58,'Colinas Pardas');
insert into Realm (realmId, ExternalIdentifier) values (-59,'Confrérie du Thorium');
insert into Realm (realmId, ExternalIdentifier) values (-60,'Conseil des Ombres');
insert into Realm (realmId, ExternalIdentifier) values (-61,'Crushridge');
insert into Realm (realmId, ExternalIdentifier) values (-62,'Culte de la Rive noire');
insert into Realm (realmId, ExternalIdentifier) values (-63,'Daggerspine');
insert into Realm (realmId, ExternalIdentifier) values (-64,'Dalaran');
insert into Realm (realmId, ExternalIdentifier) values (-65,'Dalvengyr');
insert into Realm (realmId, ExternalIdentifier) values (-66,'Darkmoon Faire');
insert into Realm (realmId, ExternalIdentifier) values (-67,'Darksorrow');
insert into Realm (realmId, ExternalIdentifier) values (-68,'Darkspear');
insert into Realm (realmId, ExternalIdentifier) values (-69,'Das Konsortium');
insert into Realm (realmId, ExternalIdentifier) values (-70,'Das Syndikat');
insert into Realm (realmId, ExternalIdentifier) values (-71,'Deathguard');
insert into Realm (realmId, ExternalIdentifier) values (-72,'Deathweaver');
insert into Realm (realmId, ExternalIdentifier) values (-73,'Deathwing');
insert into Realm (realmId, ExternalIdentifier) values (-74,'Deepholm');
insert into Realm (realmId, ExternalIdentifier) values (-75,'Defias Brotherhood');
insert into Realm (realmId, ExternalIdentifier) values (-76,'Dentarg');
insert into Realm (realmId, ExternalIdentifier) values (-77,'Der abyssische Rat');
insert into Realm (realmId, ExternalIdentifier) values (-78,'Der Mithrilorden');
insert into Realm (realmId, ExternalIdentifier) values (-79,'Der Rat von Dalaran');
insert into Realm (realmId, ExternalIdentifier) values (-80,'Destromath');
insert into Realm (realmId, ExternalIdentifier) values (-81,'Dethecus');
insert into Realm (realmId, ExternalIdentifier) values (-82,'Die Aldor');
insert into Realm (realmId, ExternalIdentifier) values (-83,'Die Arguswacht');
insert into Realm (realmId, ExternalIdentifier) values (-84,'Die ewige Wacht');
insert into Realm (realmId, ExternalIdentifier) values (-85,'Die Nachtwache');
insert into Realm (realmId, ExternalIdentifier) values (-86,'Die Silberne Hand');
insert into Realm (realmId, ExternalIdentifier) values (-87,'Die Todeskrallen');
insert into Realm (realmId, ExternalIdentifier) values (-88,'Doomhammer');
insert into Realm (realmId, ExternalIdentifier) values (-89,'Draenor');
insert into Realm (realmId, ExternalIdentifier) values (-90,'Dragonblight');
insert into Realm (realmId, ExternalIdentifier) values (-91,'Dragonmaw');
insert into Realm (realmId, ExternalIdentifier) values (-92,'Drak''thul');
insert into Realm (realmId, ExternalIdentifier) values (-93,'Drek''Thar');
insert into Realm (realmId, ExternalIdentifier) values (-94,'Dun Modr');
insert into Realm (realmId, ExternalIdentifier) values (-95,'Dun Morogh');
insert into Realm (realmId, ExternalIdentifier) values (-96,'Dunemaul');
insert into Realm (realmId, ExternalIdentifier) values (-97,'Durotan');
insert into Realm (realmId, ExternalIdentifier) values (-98,'Earthen Ring');
insert into Realm (realmId, ExternalIdentifier) values (-99,'Echsenkessel');
insert into Realm (realmId, ExternalIdentifier) values (-100,'Eitrigg');
insert into Realm (realmId, ExternalIdentifier) values (-101,'Eldre''Thalas');
insert into Realm (realmId, ExternalIdentifier) values (-102,'Elune');
insert into Realm (realmId, ExternalIdentifier) values (-103,'Emerald Dream');
insert into Realm (realmId, ExternalIdentifier) values (-104,'Emeriss');
insert into Realm (realmId, ExternalIdentifier) values (-105,'Eonar');
insert into Realm (realmId, ExternalIdentifier) values (-106,'Eredar');
insert into Realm (realmId, ExternalIdentifier) values (-107,'Eversong');
insert into Realm (realmId, ExternalIdentifier) values (-108,'Executus');
insert into Realm (realmId, ExternalIdentifier) values (-109,'Exodar');
insert into Realm (realmId, ExternalIdentifier) values (-110,'Festung der Stürme');
insert into Realm (realmId, ExternalIdentifier) values (-111,'Fordragon');
insert into Realm (realmId, ExternalIdentifier) values (-112,'Forscherliga');
insert into Realm (realmId, ExternalIdentifier) values (-113,'Frostmane');
insert into Realm (realmId, ExternalIdentifier) values (-114,'Frostmourne');
insert into Realm (realmId, ExternalIdentifier) values (-115,'Frostwhisper');
insert into Realm (realmId, ExternalIdentifier) values (-116,'Frostwolf');
insert into Realm (realmId, ExternalIdentifier) values (-117,'Galakrond');
insert into Realm (realmId, ExternalIdentifier) values (-118,'Garona');
insert into Realm (realmId, ExternalIdentifier) values (-119,'Garrosh');
insert into Realm (realmId, ExternalIdentifier) values (-120,'Genjuros');
insert into Realm (realmId, ExternalIdentifier) values (-121,'Ghostlands');
insert into Realm (realmId, ExternalIdentifier) values (-122,'Gilneas');
insert into Realm (realmId, ExternalIdentifier) values (-123,'Goldrinn');
insert into Realm (realmId, ExternalIdentifier) values (-124,'Gordunni');
insert into Realm (realmId, ExternalIdentifier) values (-125,'Gorgonnash');
insert into Realm (realmId, ExternalIdentifier) values (-126,'Greymane');
insert into Realm (realmId, ExternalIdentifier) values (-127,'Grim Batol');
insert into Realm (realmId, ExternalIdentifier) values (-128,'Grom');
insert into Realm (realmId, ExternalIdentifier) values (-129,'Gul''dan');
insert into Realm (realmId, ExternalIdentifier) values (-130,'Hakkar');
insert into Realm (realmId, ExternalIdentifier) values (-131,'Haomarush');
insert into Realm (realmId, ExternalIdentifier) values (-132,'Hellfire');
insert into Realm (realmId, ExternalIdentifier) values (-133,'Hellscream');
insert into Realm (realmId, ExternalIdentifier) values (-134,'Howling Fjord');
insert into Realm (realmId, ExternalIdentifier) values (-135,'Hyjal');
insert into Realm (realmId, ExternalIdentifier) values (-136,'Illidan');
insert into Realm (realmId, ExternalIdentifier) values (-137,'Jaedenar');
insert into Realm (realmId, ExternalIdentifier) values (-138,'Kael''thas');
insert into Realm (realmId, ExternalIdentifier) values (-139,'Karazhan');
insert into Realm (realmId, ExternalIdentifier) values (-140,'Kargath');
insert into Realm (realmId, ExternalIdentifier) values (-141,'Kazzak');
insert into Realm (realmId, ExternalIdentifier) values (-142,'Kel''Thuzad');
insert into Realm (realmId, ExternalIdentifier) values (-143,'Khadgar');
insert into Realm (realmId, ExternalIdentifier) values (-144,'Khaz Modan');
insert into Realm (realmId, ExternalIdentifier) values (-145,'Khaz''goroth');
insert into Realm (realmId, ExternalIdentifier) values (-146,'Kil''jaeden');
insert into Realm (realmId, ExternalIdentifier) values (-147,'Kilrogg');
insert into Realm (realmId, ExternalIdentifier) values (-148,'Kirin Tor');
insert into Realm (realmId, ExternalIdentifier) values (-149,'Kor''gall');
insert into Realm (realmId, ExternalIdentifier) values (-150,'Krag''jin');
insert into Realm (realmId, ExternalIdentifier) values (-151,'Krasus');
insert into Realm (realmId, ExternalIdentifier) values (-152,'Kul Tiras');
insert into Realm (realmId, ExternalIdentifier) values (-153,'Kult der Verdammten');
insert into Realm (realmId, ExternalIdentifier) values (-154,'La Croisade écarlate');
insert into Realm (realmId, ExternalIdentifier) values (-155,'Laughing Skull');
insert into Realm (realmId, ExternalIdentifier) values (-156,'Les Clairvoyants');
insert into Realm (realmId, ExternalIdentifier) values (-157,'Les Sentinelles');
insert into Realm (realmId, ExternalIdentifier) values (-158,'Lich King');
insert into Realm (realmId, ExternalIdentifier) values (-159,'Lightbringer');
insert into Realm (realmId, ExternalIdentifier) values (-160,'Lightning''s Blade');
insert into Realm (realmId, ExternalIdentifier) values (-161,'Lordaeron');
insert into Realm (realmId, ExternalIdentifier) values (-162,'Los Errantes');
insert into Realm (realmId, ExternalIdentifier) values (-163,'Lothar');
insert into Realm (realmId, ExternalIdentifier) values (-164,'Madmortem');
insert into Realm (realmId, ExternalIdentifier) values (-165,'Magtheridon');
insert into Realm (realmId, ExternalIdentifier) values (-166,'Mal''Ganis');
insert into Realm (realmId, ExternalIdentifier) values (-167,'Malfurion');
insert into Realm (realmId, ExternalIdentifier) values (-168,'Malorne');
insert into Realm (realmId, ExternalIdentifier) values (-169,'Malygos');
insert into Realm (realmId, ExternalIdentifier) values (-170,'Mannoroth');
insert into Realm (realmId, ExternalIdentifier) values (-171,'Marécage de Zangar');
insert into Realm (realmId, ExternalIdentifier) values (-172,'Mazrigos');
insert into Realm (realmId, ExternalIdentifier) values (-173,'Medivh');
insert into Realm (realmId, ExternalIdentifier) values (-174,'Minahonda');
insert into Realm (realmId, ExternalIdentifier) values (-175,'Moonglade');
insert into Realm (realmId, ExternalIdentifier) values (-176,'Mug''thol');
insert into Realm (realmId, ExternalIdentifier) values (-177,'Nagrand');
insert into Realm (realmId, ExternalIdentifier) values (-178,'Nathrezim');
insert into Realm (realmId, ExternalIdentifier) values (-179,'Naxxramas');
insert into Realm (realmId, ExternalIdentifier) values (-180,'Nazjatar');
insert into Realm (realmId, ExternalIdentifier) values (-181,'Nefarian');
insert into Realm (realmId, ExternalIdentifier) values (-182,'Nemesis');
insert into Realm (realmId, ExternalIdentifier) values (-183,'Neptulon');
insert into Realm (realmId, ExternalIdentifier) values (-184,'Ner''zhul');
insert into Realm (realmId, ExternalIdentifier) values (-185,'Nera''thor');
insert into Realm (realmId, ExternalIdentifier) values (-186,'Nethersturm');
insert into Realm (realmId, ExternalIdentifier) values (-187,'Nordrassil');
insert into Realm (realmId, ExternalIdentifier) values (-188,'Norgannon');
insert into Realm (realmId, ExternalIdentifier) values (-189,'Nozdormu');
insert into Realm (realmId, ExternalIdentifier) values (-190,'Onyxia');
insert into Realm (realmId, ExternalIdentifier) values (-191,'Outland');
insert into Realm (realmId, ExternalIdentifier) values (-192,'Perenolde');
insert into Realm (realmId, ExternalIdentifier) values (-193,'Pozzo dell''Eternità');
insert into Realm (realmId, ExternalIdentifier) values (-194,'Proudmoore');
insert into Realm (realmId, ExternalIdentifier) values (-195,'Quel''Thalas');
insert into Realm (realmId, ExternalIdentifier) values (-196,'Ragnaros');
insert into Realm (realmId, ExternalIdentifier) values (-197,'Rajaxx');
insert into Realm (realmId, ExternalIdentifier) values (-198,'Rashgarroth');
insert into Realm (realmId, ExternalIdentifier) values (-199,'Ravencrest');
insert into Realm (realmId, ExternalIdentifier) values (-200,'Ravenholdt');
insert into Realm (realmId, ExternalIdentifier) values (-201,'Razuvious');
insert into Realm (realmId, ExternalIdentifier) values (-202,'Rexxar');
insert into Realm (realmId, ExternalIdentifier) values (-203,'Runetotem');
insert into Realm (realmId, ExternalIdentifier) values (-204,'Sanguino');
insert into Realm (realmId, ExternalIdentifier) values (-205,'Sargeras');
insert into Realm (realmId, ExternalIdentifier) values (-206,'Saurfang');
insert into Realm (realmId, ExternalIdentifier) values (-207,'Scarshield Legion');
insert into Realm (realmId, ExternalIdentifier) values (-208,'Sen''jin');
insert into Realm (realmId, ExternalIdentifier) values (-209,'Shadowsong');
insert into Realm (realmId, ExternalIdentifier) values (-210,'Shattered Halls');
insert into Realm (realmId, ExternalIdentifier) values (-211,'Shattered Hand');
insert into Realm (realmId, ExternalIdentifier) values (-212,'Shattrath');
insert into Realm (realmId, ExternalIdentifier) values (-213,'Shen''dralar');
insert into Realm (realmId, ExternalIdentifier) values (-214,'Silvermoon');
insert into Realm (realmId, ExternalIdentifier) values (-215,'Sinstralis');
insert into Realm (realmId, ExternalIdentifier) values (-216,'Skullcrusher');
insert into Realm (realmId, ExternalIdentifier) values (-217,'Soulflayer');
insert into Realm (realmId, ExternalIdentifier) values (-218,'Spinebreaker');
insert into Realm (realmId, ExternalIdentifier) values (-219,'Sporeggar');
insert into Realm (realmId, ExternalIdentifier) values (-220,'Steamwheedle Cartel');
insert into Realm (realmId, ExternalIdentifier) values (-221,'Stormrage');
insert into Realm (realmId, ExternalIdentifier) values (-222,'Stormreaver');
insert into Realm (realmId, ExternalIdentifier) values (-223,'Stormscale');
insert into Realm (realmId, ExternalIdentifier) values (-224,'Sunstrider');
insert into Realm (realmId, ExternalIdentifier) values (-225,'Sylvanas');
insert into Realm (realmId, ExternalIdentifier) values (-226,'Taerar');
insert into Realm (realmId, ExternalIdentifier) values (-227,'Talnivarr');
insert into Realm (realmId, ExternalIdentifier) values (-228,'Tarren Mill');
insert into Realm (realmId, ExternalIdentifier) values (-229,'Teldrassil');
insert into Realm (realmId, ExternalIdentifier) values (-230,'Temple noir');
insert into Realm (realmId, ExternalIdentifier) values (-231,'Terenas');
insert into Realm (realmId, ExternalIdentifier) values (-232,'Terokkar');
insert into Realm (realmId, ExternalIdentifier) values (-233,'Terrordar');
insert into Realm (realmId, ExternalIdentifier) values (-234,'The Maelstrom');
insert into Realm (realmId, ExternalIdentifier) values (-235,'The Sha''tar');
insert into Realm (realmId, ExternalIdentifier) values (-236,'The Venture Co');
insert into Realm (realmId, ExternalIdentifier) values (-237,'Theradras');
insert into Realm (realmId, ExternalIdentifier) values (-238,'Thermaplugg');
insert into Realm (realmId, ExternalIdentifier) values (-239,'Thrall');
insert into Realm (realmId, ExternalIdentifier) values (-240,'Throk''Feroth');
insert into Realm (realmId, ExternalIdentifier) values (-241,'Thunderhorn');
insert into Realm (realmId, ExternalIdentifier) values (-242,'Tichondrius');
insert into Realm (realmId, ExternalIdentifier) values (-243,'Tirion');
insert into Realm (realmId, ExternalIdentifier) values (-244,'Todeswache');
insert into Realm (realmId, ExternalIdentifier) values (-245,'Trollbane');
insert into Realm (realmId, ExternalIdentifier) values (-246,'Turalyon');
insert into Realm (realmId, ExternalIdentifier) values (-247,'Twilight''s Hammer');
insert into Realm (realmId, ExternalIdentifier) values (-248,'Twisting Nether');
insert into Realm (realmId, ExternalIdentifier) values (-249,'Tyrande');
insert into Realm (realmId, ExternalIdentifier) values (-250,'Uldaman');
insert into Realm (realmId, ExternalIdentifier) values (-251,'Ulduar');
insert into Realm (realmId, ExternalIdentifier) values (-252,'Uldum');
insert into Realm (realmId, ExternalIdentifier) values (-253,'Un''Goro');
insert into Realm (realmId, ExternalIdentifier) values (-254,'Varimathras');
insert into Realm (realmId, ExternalIdentifier) values (-255,'Vashj');
insert into Realm (realmId, ExternalIdentifier) values (-256,'Vek''lor');
insert into Realm (realmId, ExternalIdentifier) values (-257,'Vek''nilash');
insert into Realm (realmId, ExternalIdentifier) values (-258,'Vol''jin');
insert into Realm (realmId, ExternalIdentifier) values (-259,'Wildhammer');
insert into Realm (realmId, ExternalIdentifier) values (-260,'Wrathbringer');
insert into Realm (realmId, ExternalIdentifier) values (-261,'Xavius');
insert into Realm (realmId, ExternalIdentifier) values (-262,'Ysera');
insert into Realm (realmId, ExternalIdentifier) values (-263,'Ysondre');
insert into Realm (realmId, ExternalIdentifier) values (-264,'Zenedar');
insert into Realm (realmId, ExternalIdentifier) values (-265,'Zirkel des Cenarius');
insert into Realm (realmId, ExternalIdentifier) values (-266,'Zul''jin');
insert into Realm (realmId, ExternalIdentifier) values (-267,'Zuluhed ');
insert into Realm (realmId, ExternalIdentifier) values (-268,'Akama');
insert into Realm (realmId, ExternalIdentifier) values (-269,'Altar of Storms');
insert into Realm (realmId, ExternalIdentifier) values (-270,'Alterac Mountains');
insert into Realm (realmId, ExternalIdentifier) values (-271,'Andorhal');
insert into Realm (realmId, ExternalIdentifier) values (-272,'Anvilmar');
insert into Realm (realmId, ExternalIdentifier) values (-273,'Azgalor');
insert into Realm (realmId, ExternalIdentifier) values (-274,'Azralon');
insert into Realm (realmId, ExternalIdentifier) values (-275,'Barthilas');
insert into Realm (realmId, ExternalIdentifier) values (-276,'Black Dragonflight');
insert into Realm (realmId, ExternalIdentifier) values (-277,'Blackwater Raiders');
insert into Realm (realmId, ExternalIdentifier) values (-278,'Blackwing Lair');
insert into Realm (realmId, ExternalIdentifier) values (-279,'Bleeding Hollow');
insert into Realm (realmId, ExternalIdentifier) values (-280,'Blood Furnace');
insert into Realm (realmId, ExternalIdentifier) values (-281,'Bonechewer');
insert into Realm (realmId, ExternalIdentifier) values (-282,'Burning Legion');
insert into Realm (realmId, ExternalIdentifier) values (-283,'Caelestrasz');
insert into Realm (realmId, ExternalIdentifier) values (-284,'Cairne');
insert into Realm (realmId, ExternalIdentifier) values (-285,'Cenarion Circle');
insert into Realm (realmId, ExternalIdentifier) values (-286,'Cenarius');
insert into Realm (realmId, ExternalIdentifier) values (-287,'Coilfang');
insert into Realm (realmId, ExternalIdentifier) values (-288,'Dark Iron');
insert into Realm (realmId, ExternalIdentifier) values (-289,'Darrowmere');
insert into Realm (realmId, ExternalIdentifier) values (-290,'Dath''Remar');
insert into Realm (realmId, ExternalIdentifier) values (-291,'Dawnbringer');
insert into Realm (realmId, ExternalIdentifier) values (-292,'Demon Soul');
insert into Realm (realmId, ExternalIdentifier) values (-293,'Detheroc');
insert into Realm (realmId, ExternalIdentifier) values (-294,'Drak''Tharon');
insert into Realm (realmId, ExternalIdentifier) values (-295,'Draka');
insert into Realm (realmId, ExternalIdentifier) values (-296,'Drakkari');
insert into Realm (realmId, ExternalIdentifier) values (-297,'Dreadmaul');
insert into Realm (realmId, ExternalIdentifier) values (-298,'Drenden');
insert into Realm (realmId, ExternalIdentifier) values (-299,'Duskwood');
insert into Realm (realmId, ExternalIdentifier) values (-300,'Echo Isles');
insert into Realm (realmId, ExternalIdentifier) values (-301,'Farstriders');
insert into Realm (realmId, ExternalIdentifier) values (-302,'Feathermoon');
insert into Realm (realmId, ExternalIdentifier) values (-303,'Fenris');
insert into Realm (realmId, ExternalIdentifier) values (-304,'Firetree');
insert into Realm (realmId, ExternalIdentifier) values (-305,'Fizzcrank');
insert into Realm (realmId, ExternalIdentifier) values (-306,'Gallywix');
insert into Realm (realmId, ExternalIdentifier) values (-307,'Garithos');
insert into Realm (realmId, ExternalIdentifier) values (-308,'Gnomeregan');
insert into Realm (realmId, ExternalIdentifier) values (-309,'Gorefiend');
insert into Realm (realmId, ExternalIdentifier) values (-310,'Grizzly Hills');
insert into Realm (realmId, ExternalIdentifier) values (-311,'Gundrak');
insert into Realm (realmId, ExternalIdentifier) values (-312,'Gurubashi');
insert into Realm (realmId, ExternalIdentifier) values (-313,'Hydraxis');
insert into Realm (realmId, ExternalIdentifier) values (-314,'Icecrown');
insert into Realm (realmId, ExternalIdentifier) values (-315,'Jubei''Thos');
insert into Realm (realmId, ExternalIdentifier) values (-316,'Kalecgos');
insert into Realm (realmId, ExternalIdentifier) values (-317,'Korgath');
insert into Realm (realmId, ExternalIdentifier) values (-318,'Korialstrasz');
insert into Realm (realmId, ExternalIdentifier) values (-319,'Lethon');
insert into Realm (realmId, ExternalIdentifier) values (-320,'Lightninghoof');
insert into Realm (realmId, ExternalIdentifier) values (-321,'Llane');
insert into Realm (realmId, ExternalIdentifier) values (-322,'Madoran');
insert into Realm (realmId, ExternalIdentifier) values (-323,'Maelstrom');
insert into Realm (realmId, ExternalIdentifier) values (-324,'Maiev');
insert into Realm (realmId, ExternalIdentifier) values (-325,'Misha');
insert into Realm (realmId, ExternalIdentifier) values (-326,'Mok''Nathal');
insert into Realm (realmId, ExternalIdentifier) values (-327,'Moon Guard');
insert into Realm (realmId, ExternalIdentifier) values (-328,'Moonrunner');
insert into Realm (realmId, ExternalIdentifier) values (-329,'Muradin');
insert into Realm (realmId, ExternalIdentifier) values (-330,'Nazgrel');
insert into Realm (realmId, ExternalIdentifier) values (-331,'Nesingwary');
insert into Realm (realmId, ExternalIdentifier) values (-332,'Quel''dorei');
insert into Realm (realmId, ExternalIdentifier) values (-333,'Rivendare');
insert into Realm (realmId, ExternalIdentifier) values (-334,'Scarlet Crusade');
insert into Realm (realmId, ExternalIdentifier) values (-335,'Scilla');
insert into Realm (realmId, ExternalIdentifier) values (-336,'Sentinels');
insert into Realm (realmId, ExternalIdentifier) values (-337,'Shadow Council');
insert into Realm (realmId, ExternalIdentifier) values (-338,'Shadowmoon');
insert into Realm (realmId, ExternalIdentifier) values (-339,'Shandris');
insert into Realm (realmId, ExternalIdentifier) values (-340,'Shu''halo');
insert into Realm (realmId, ExternalIdentifier) values (-341,'Silver Hand');
insert into Realm (realmId, ExternalIdentifier) values (-342,'Sisters of Elune');
insert into Realm (realmId, ExternalIdentifier) values (-343,'Skywall');
insert into Realm (realmId, ExternalIdentifier) values (-344,'Smolderthorn');
insert into Realm (realmId, ExternalIdentifier) values (-345,'Spirestone');
insert into Realm (realmId, ExternalIdentifier) values (-346,'Staghelm');
insert into Realm (realmId, ExternalIdentifier) values (-347,'Stonemaul');
insert into Realm (realmId, ExternalIdentifier) values (-348,'Suramar');
insert into Realm (realmId, ExternalIdentifier) values (-349,'Tanaris');
insert into Realm (realmId, ExternalIdentifier) values (-350,'Thaurissan');
insert into Realm (realmId, ExternalIdentifier) values (-351,'The Forgotten Coast');
insert into Realm (realmId, ExternalIdentifier) values (-352,'The Scryers');
insert into Realm (realmId, ExternalIdentifier) values (-353,'The Underbog');
insert into Realm (realmId, ExternalIdentifier) values (-354,'Thorium Brotherhood');
insert into Realm (realmId, ExternalIdentifier) values (-355,'Thunderlord');
insert into Realm (realmId, ExternalIdentifier) values (-356,'Tol Barad');
insert into Realm (realmId, ExternalIdentifier) values (-357,'Tortheldrin');
insert into Realm (realmId, ExternalIdentifier) values (-358,'Undermine');
insert into Realm (realmId, ExternalIdentifier) values (-359,'Ursin');
insert into Realm (realmId, ExternalIdentifier) values (-360,'Uther');
insert into Realm (realmId, ExternalIdentifier) values (-361,'Velen');
insert into Realm (realmId, ExternalIdentifier) values (-362,'Warsong');
insert into Realm (realmId, ExternalIdentifier) values (-363,'Whisperwind');
insert into Realm (realmId, ExternalIdentifier) values (-364,'Windrunner');
insert into Realm (realmId, ExternalIdentifier) values (-365,'Winterhoof');
insert into Realm (realmId, ExternalIdentifier) values (-366,'Wyrmrest Accord');
insert into Realm (realmId, ExternalIdentifier) values (-367,'Zangarmarsh');

alter table auction add foreign key (ownerRealmId) references Public.Realm(realmId);