package wowData.business.support;

import java.util.HashMap;
import java.util.Map;

public class Realm {

	private String name;
	private RegionSelection regionSelection;
	
	public static final Map<String, Integer> realmNameIdMap;
	
	static {
		realmNameIdMap = new HashMap<>();
		realmNameIdMap.put("Aegwynn", Integer.valueOf(-1));
		realmNameIdMap.put("AeriePeak", Integer.valueOf(-2));
		realmNameIdMap.put("Agamaggan", Integer.valueOf(-3));
		realmNameIdMap.put("Aggra(Português)", Integer.valueOf(-4));
		realmNameIdMap.put("Aggramar", Integer.valueOf(-5));
		realmNameIdMap.put("Ahn'Qiraj", Integer.valueOf(-6));
		realmNameIdMap.put("Al'Akir", Integer.valueOf(-7));
		realmNameIdMap.put("Alexstrasza", Integer.valueOf(-8));
		realmNameIdMap.put("Alleria", Integer.valueOf(-9));
		realmNameIdMap.put("Aerie Peak", Integer.valueOf(-10));
		realmNameIdMap.put("Aggra (Português)", Integer.valueOf(-11));
		realmNameIdMap.put("Alonsus", Integer.valueOf(-12));
		realmNameIdMap.put("Aman'Thul", Integer.valueOf(-13));
		realmNameIdMap.put("Ambossar", Integer.valueOf(-14));
		realmNameIdMap.put("Anachronos", Integer.valueOf(-15));
		realmNameIdMap.put("Anetheron", Integer.valueOf(-16));
		realmNameIdMap.put("Antonidas", Integer.valueOf(-17));
		realmNameIdMap.put("Anub'arak", Integer.valueOf(-18));
		realmNameIdMap.put("Arak-arahm", Integer.valueOf(-19));
		realmNameIdMap.put("Arathi", Integer.valueOf(-20));
		realmNameIdMap.put("Arathor", Integer.valueOf(-21));
		realmNameIdMap.put("Archimonde", Integer.valueOf(-22));
		realmNameIdMap.put("Area 52", Integer.valueOf(-23));
		realmNameIdMap.put("Argent Dawn", Integer.valueOf(-24));
		realmNameIdMap.put("Arthas", Integer.valueOf(-25));
		realmNameIdMap.put("Arygos", Integer.valueOf(-26));
		realmNameIdMap.put("Ashenvale", Integer.valueOf(-27));
		realmNameIdMap.put("Aszune", Integer.valueOf(-28));
		realmNameIdMap.put("Auchindoun", Integer.valueOf(-29));
		realmNameIdMap.put("Azjol-Nerub", Integer.valueOf(-30));
		realmNameIdMap.put("Azshara", Integer.valueOf(-31));
		realmNameIdMap.put("Azuregos", Integer.valueOf(-32));
		realmNameIdMap.put("Azuremyst", Integer.valueOf(-33));
		realmNameIdMap.put("Baelgun", Integer.valueOf(-34));
		realmNameIdMap.put("Balnazzar", Integer.valueOf(-35));
		realmNameIdMap.put("Blackhand", Integer.valueOf(-36));
		realmNameIdMap.put("Blackmoore", Integer.valueOf(-37));
		realmNameIdMap.put("Blackrock", Integer.valueOf(-38));
		realmNameIdMap.put("Blackscar", Integer.valueOf(-39));
		realmNameIdMap.put("Blade's Edge", Integer.valueOf(-40));
		realmNameIdMap.put("Bladefist", Integer.valueOf(-41));
		realmNameIdMap.put("Bloodfeather", Integer.valueOf(-42));
		realmNameIdMap.put("Bloodhoof", Integer.valueOf(-43));
		realmNameIdMap.put("Bloodscalp", Integer.valueOf(-44));
		realmNameIdMap.put("Blutkessel", Integer.valueOf(-45));
		realmNameIdMap.put("Booty Bay", Integer.valueOf(-46));
		realmNameIdMap.put("Borean Tundra", Integer.valueOf(-47));
		realmNameIdMap.put("Boulderfist", Integer.valueOf(-48));
		realmNameIdMap.put("Bronze Dragonflight", Integer.valueOf(-49));
		realmNameIdMap.put("Bronzebeard", Integer.valueOf(-50));
		realmNameIdMap.put("Burning Blade", Integer.valueOf(-51));
		realmNameIdMap.put("Burning Steppes", Integer.valueOf(-52));
		realmNameIdMap.put("C'Thun", Integer.valueOf(-53));
		realmNameIdMap.put("Chamber of Aspects", Integer.valueOf(-54));
		realmNameIdMap.put("Chants éternels", Integer.valueOf(-55));
		realmNameIdMap.put("Cho'gall", Integer.valueOf(-56));
		realmNameIdMap.put("Chromaggus", Integer.valueOf(-57));
		realmNameIdMap.put("Colinas Pardas", Integer.valueOf(-58));
		realmNameIdMap.put("Confrérie du Thorium", Integer.valueOf(-59));
		realmNameIdMap.put("Conseil des Ombres", Integer.valueOf(-60));
		realmNameIdMap.put("Crushridge", Integer.valueOf(-61));
		realmNameIdMap.put("Culte de la Rive noire", Integer.valueOf(-62));
		realmNameIdMap.put("Daggerspine", Integer.valueOf(-63));
		realmNameIdMap.put("Dalaran", Integer.valueOf(-64));
		realmNameIdMap.put("Dalvengyr", Integer.valueOf(-65));
		realmNameIdMap.put("Darkmoon Faire", Integer.valueOf(-66));
		realmNameIdMap.put("Darksorrow", Integer.valueOf(-67));
		realmNameIdMap.put("Darkspear", Integer.valueOf(-68));
		realmNameIdMap.put("Das Konsortium", Integer.valueOf(-69));
		realmNameIdMap.put("Das Syndikat", Integer.valueOf(-70));
		realmNameIdMap.put("Deathguard", Integer.valueOf(-71));
		realmNameIdMap.put("Deathweaver", Integer.valueOf(-72));
		realmNameIdMap.put("Deathwing", Integer.valueOf(-73));
		realmNameIdMap.put("Deepholm", Integer.valueOf(-74));
		realmNameIdMap.put("Defias Brotherhood", Integer.valueOf(-75));
		realmNameIdMap.put("Dentarg", Integer.valueOf(-76));
		realmNameIdMap.put("Der abyssische Rat", Integer.valueOf(-77));
		realmNameIdMap.put("Der Mithrilorden", Integer.valueOf(-78));
		realmNameIdMap.put("Der Rat von Dalaran", Integer.valueOf(-79));
		realmNameIdMap.put("Destromath", Integer.valueOf(-80));
		realmNameIdMap.put("Dethecus", Integer.valueOf(-81));
		realmNameIdMap.put("Die Aldor", Integer.valueOf(-82));
		realmNameIdMap.put("Die Arguswacht", Integer.valueOf(-83));
		realmNameIdMap.put("Die ewige Wacht", Integer.valueOf(-84));
		realmNameIdMap.put("Die Nachtwache", Integer.valueOf(-85));
		realmNameIdMap.put("Die Silberne Hand", Integer.valueOf(-86));
		realmNameIdMap.put("Die Todeskrallen", Integer.valueOf(-87));
		realmNameIdMap.put("Doomhammer", Integer.valueOf(-88));
		realmNameIdMap.put("Draenor", Integer.valueOf(-89));
		realmNameIdMap.put("Dragonblight", Integer.valueOf(-90));
		realmNameIdMap.put("Dragonmaw", Integer.valueOf(-91));
		realmNameIdMap.put("Drak'thul", Integer.valueOf(-92));
		realmNameIdMap.put("Drek'Thar", Integer.valueOf(-93));
		realmNameIdMap.put("Dun Modr", Integer.valueOf(-94));
		realmNameIdMap.put("Dun Morogh", Integer.valueOf(-95));
		realmNameIdMap.put("Dunemaul", Integer.valueOf(-96));
		realmNameIdMap.put("Durotan", Integer.valueOf(-97));
		realmNameIdMap.put("Earthen Ring", Integer.valueOf(-98));
		realmNameIdMap.put("Echsenkessel", Integer.valueOf(-99));
		realmNameIdMap.put("Eitrigg", Integer.valueOf(-100));
		realmNameIdMap.put("Eldre'Thalas", Integer.valueOf(-101));
		realmNameIdMap.put("Elune", Integer.valueOf(-102));
		realmNameIdMap.put("Emerald Dream", Integer.valueOf(-103));
		realmNameIdMap.put("Emeriss", Integer.valueOf(-104));
		realmNameIdMap.put("Eonar", Integer.valueOf(-105));
		realmNameIdMap.put("Eredar", Integer.valueOf(-106));
		realmNameIdMap.put("Eversong", Integer.valueOf(-107));
		realmNameIdMap.put("Executus", Integer.valueOf(-108));
		realmNameIdMap.put("Exodar", Integer.valueOf(-109));
		realmNameIdMap.put("Festung der Stürme", Integer.valueOf(-110));
		realmNameIdMap.put("Fordragon", Integer.valueOf(-111));
		realmNameIdMap.put("Forscherliga", Integer.valueOf(-112));
		realmNameIdMap.put("Frostmane", Integer.valueOf(-113));
		realmNameIdMap.put("Frostmourne", Integer.valueOf(-114));
		realmNameIdMap.put("Frostwhisper", Integer.valueOf(-115));
		realmNameIdMap.put("Frostwolf", Integer.valueOf(-116));
		realmNameIdMap.put("Galakrond", Integer.valueOf(-117));
		realmNameIdMap.put("Garona", Integer.valueOf(-118));
		realmNameIdMap.put("Garrosh", Integer.valueOf(-119));
		realmNameIdMap.put("Genjuros", Integer.valueOf(-120));
		realmNameIdMap.put("Ghostlands", Integer.valueOf(-121));
		realmNameIdMap.put("Gilneas", Integer.valueOf(-122));
		realmNameIdMap.put("Goldrinn", Integer.valueOf(-123));
		realmNameIdMap.put("Gordunni", Integer.valueOf(-124));
		realmNameIdMap.put("Gorgonnash", Integer.valueOf(-125));
		realmNameIdMap.put("Greymane", Integer.valueOf(-126));
		realmNameIdMap.put("Grim Batol", Integer.valueOf(-127));
		realmNameIdMap.put("Grom", Integer.valueOf(-128));
		realmNameIdMap.put("Gul'dan", Integer.valueOf(-129));
		realmNameIdMap.put("Hakkar", Integer.valueOf(-130));
		realmNameIdMap.put("Haomarush", Integer.valueOf(-131));
		realmNameIdMap.put("Hellfire", Integer.valueOf(-132));
		realmNameIdMap.put("Hellscream", Integer.valueOf(-133));
		realmNameIdMap.put("Howling Fjord", Integer.valueOf(-134));
		realmNameIdMap.put("Hyjal", Integer.valueOf(-135));
		realmNameIdMap.put("Illidan", Integer.valueOf(-136));
		realmNameIdMap.put("Jaedenar", Integer.valueOf(-137));
		realmNameIdMap.put("Kael'thas", Integer.valueOf(-138));
		realmNameIdMap.put("Karazhan", Integer.valueOf(-139));
		realmNameIdMap.put("Kargath", Integer.valueOf(-140));
		realmNameIdMap.put("Kazzak", Integer.valueOf(-141));
		realmNameIdMap.put("Kel'Thuzad", Integer.valueOf(-142));
		realmNameIdMap.put("Khadgar", Integer.valueOf(-143));
		realmNameIdMap.put("Khaz Modan", Integer.valueOf(-144));
		realmNameIdMap.put("Khaz'goroth", Integer.valueOf(-145));
		realmNameIdMap.put("Kil'jaeden", Integer.valueOf(-146));
		realmNameIdMap.put("Kilrogg", Integer.valueOf(-147));
		realmNameIdMap.put("Kirin Tor", Integer.valueOf(-148));
		realmNameIdMap.put("Kor'gall", Integer.valueOf(-149));
		realmNameIdMap.put("Krag'jin", Integer.valueOf(-150));
		realmNameIdMap.put("Krasus", Integer.valueOf(-151));
		realmNameIdMap.put("Kul Tiras", Integer.valueOf(-152));
		realmNameIdMap.put("Kult der Verdammten", Integer.valueOf(-153));
		realmNameIdMap.put("La Croisade écarlate", Integer.valueOf(-154));
		realmNameIdMap.put("Laughing Skull", Integer.valueOf(-155));
		realmNameIdMap.put("Les Clairvoyants", Integer.valueOf(-156));
		realmNameIdMap.put("Les Sentinelles", Integer.valueOf(-157));
		realmNameIdMap.put("Lich King", Integer.valueOf(-158));
		realmNameIdMap.put("Lightbringer", Integer.valueOf(-159));
		realmNameIdMap.put("Lightning's Blade", Integer.valueOf(-160));
		realmNameIdMap.put("Lordaeron", Integer.valueOf(-161));
		realmNameIdMap.put("Los Errantes", Integer.valueOf(-162));
		realmNameIdMap.put("Lothar", Integer.valueOf(-163));
		realmNameIdMap.put("Madmortem", Integer.valueOf(-164));
		realmNameIdMap.put("Magtheridon", Integer.valueOf(-165));
		realmNameIdMap.put("Mal'Ganis", Integer.valueOf(-166));
		realmNameIdMap.put("Malfurion", Integer.valueOf(-167));
		realmNameIdMap.put("Malorne", Integer.valueOf(-168));
		realmNameIdMap.put("Malygos", Integer.valueOf(-169));
		realmNameIdMap.put("Mannoroth", Integer.valueOf(-170));
		realmNameIdMap.put("Marécage de Zangar", Integer.valueOf(-171));
		realmNameIdMap.put("Mazrigos", Integer.valueOf(-172));
		realmNameIdMap.put("Medivh", Integer.valueOf(-173));
		realmNameIdMap.put("Minahonda", Integer.valueOf(-174));
		realmNameIdMap.put("Moonglade", Integer.valueOf(-175));
		realmNameIdMap.put("Mug'thol", Integer.valueOf(-176));
		realmNameIdMap.put("Nagrand", Integer.valueOf(-177));
		realmNameIdMap.put("Nathrezim", Integer.valueOf(-178));
		realmNameIdMap.put("Naxxramas", Integer.valueOf(-179));
		realmNameIdMap.put("Nazjatar", Integer.valueOf(-180));
		realmNameIdMap.put("Nefarian", Integer.valueOf(-181));
		realmNameIdMap.put("Nemesis", Integer.valueOf(-182));
		realmNameIdMap.put("Neptulon", Integer.valueOf(-183));
		realmNameIdMap.put("Ner'zhul", Integer.valueOf(-184));
		realmNameIdMap.put("Nera'thor", Integer.valueOf(-185));
		realmNameIdMap.put("Nethersturm", Integer.valueOf(-186));
		realmNameIdMap.put("Nordrassil", Integer.valueOf(-187));
		realmNameIdMap.put("Norgannon", Integer.valueOf(-188));
		realmNameIdMap.put("Nozdormu", Integer.valueOf(-189));
		realmNameIdMap.put("Onyxia", Integer.valueOf(-190));
		realmNameIdMap.put("Outland", Integer.valueOf(-191));
		realmNameIdMap.put("Perenolde", Integer.valueOf(-192));
		realmNameIdMap.put("Pozzo dell'Eternità", Integer.valueOf(-193));
		realmNameIdMap.put("Proudmoore", Integer.valueOf(-194));
		realmNameIdMap.put("Quel'Thalas", Integer.valueOf(-195));
		realmNameIdMap.put("Ragnaros", Integer.valueOf(-196));
		realmNameIdMap.put("Rajaxx", Integer.valueOf(-197));
		realmNameIdMap.put("Rashgarroth", Integer.valueOf(-198));
		realmNameIdMap.put("Ravencrest", Integer.valueOf(-199));
		realmNameIdMap.put("Ravenholdt", Integer.valueOf(-200));
		realmNameIdMap.put("Razuvious", Integer.valueOf(-201));
		realmNameIdMap.put("Rexxar", Integer.valueOf(-202));
		realmNameIdMap.put("Runetotem", Integer.valueOf(-203));
		realmNameIdMap.put("Sanguino", Integer.valueOf(-204));
		realmNameIdMap.put("Sargeras", Integer.valueOf(-205));
		realmNameIdMap.put("Saurfang", Integer.valueOf(-206));
		realmNameIdMap.put("Scarshield Legion", Integer.valueOf(-207));
		realmNameIdMap.put("Sen'jin", Integer.valueOf(-208));
		realmNameIdMap.put("Shadowsong", Integer.valueOf(-209));
		realmNameIdMap.put("Shattered Halls", Integer.valueOf(-210));
		realmNameIdMap.put("Shattered Hand", Integer.valueOf(-211));
		realmNameIdMap.put("Shattrath", Integer.valueOf(-212));
		realmNameIdMap.put("Shen'dralar", Integer.valueOf(-213));
		realmNameIdMap.put("Silvermoon", Integer.valueOf(-214));
		realmNameIdMap.put("Sinstralis", Integer.valueOf(-215));
		realmNameIdMap.put("Skullcrusher", Integer.valueOf(-216));
		realmNameIdMap.put("Soulflayer", Integer.valueOf(-217));
		realmNameIdMap.put("Spinebreaker", Integer.valueOf(-218));
		realmNameIdMap.put("Sporeggar", Integer.valueOf(-219));
		realmNameIdMap.put("Steamwheedle Cartel", Integer.valueOf(-220));
		realmNameIdMap.put("Stormrage", Integer.valueOf(-221));
		realmNameIdMap.put("Stormreaver", Integer.valueOf(-222));
		realmNameIdMap.put("Stormscale", Integer.valueOf(-223));
		realmNameIdMap.put("Sunstrider", Integer.valueOf(-224));
		realmNameIdMap.put("Sylvanas", Integer.valueOf(-225));
		realmNameIdMap.put("Taerar", Integer.valueOf(-226));
		realmNameIdMap.put("Talnivarr", Integer.valueOf(-227));
		realmNameIdMap.put("Tarren Mill", Integer.valueOf(-228));
		realmNameIdMap.put("Teldrassil", Integer.valueOf(-229));
		realmNameIdMap.put("Temple noir", Integer.valueOf(-230));
		realmNameIdMap.put("Terenas", Integer.valueOf(-231));
		realmNameIdMap.put("Terokkar", Integer.valueOf(-232));
		realmNameIdMap.put("Terrordar", Integer.valueOf(-233));
		realmNameIdMap.put("The Maelstrom", Integer.valueOf(-234));
		realmNameIdMap.put("The Sha'tar", Integer.valueOf(-235));
		realmNameIdMap.put("The Venture Co", Integer.valueOf(-236));
		realmNameIdMap.put("Theradras", Integer.valueOf(-237));
		realmNameIdMap.put("Thermaplugg", Integer.valueOf(-238));
		realmNameIdMap.put("Thrall", Integer.valueOf(-239));
		realmNameIdMap.put("Throk'Feroth", Integer.valueOf(-240));
		realmNameIdMap.put("Thunderhorn", Integer.valueOf(-241));
		realmNameIdMap.put("Tichondrius", Integer.valueOf(-242));
		realmNameIdMap.put("Tirion", Integer.valueOf(-243));
		realmNameIdMap.put("Todeswache", Integer.valueOf(-244));
		realmNameIdMap.put("Trollbane", Integer.valueOf(-245));
		realmNameIdMap.put("Turalyon", Integer.valueOf(-246));
		realmNameIdMap.put("Twilight's Hammer", Integer.valueOf(-247));
		realmNameIdMap.put("Twisting Nether", Integer.valueOf(-248));
		realmNameIdMap.put("Tyrande", Integer.valueOf(-249));
		realmNameIdMap.put("Uldaman", Integer.valueOf(-250));
		realmNameIdMap.put("Ulduar", Integer.valueOf(-251));
		realmNameIdMap.put("Uldum", Integer.valueOf(-252));
		realmNameIdMap.put("Un'Goro", Integer.valueOf(-253));
		realmNameIdMap.put("Varimathras", Integer.valueOf(-254));
		realmNameIdMap.put("Vashj", Integer.valueOf(-255));
		realmNameIdMap.put("Vek'lor", Integer.valueOf(-256));
		realmNameIdMap.put("Vek'nilash", Integer.valueOf(-257));
		realmNameIdMap.put("Vol'jin", Integer.valueOf(-258));
		realmNameIdMap.put("Wildhammer", Integer.valueOf(-259));
		realmNameIdMap.put("Wrathbringer", Integer.valueOf(-260));
		realmNameIdMap.put("Xavius", Integer.valueOf(-261));
		realmNameIdMap.put("Ysera", Integer.valueOf(-262));
		realmNameIdMap.put("Ysondre", Integer.valueOf(-263));
		realmNameIdMap.put("Zenedar", Integer.valueOf(-264));
		realmNameIdMap.put("Zirkel des Cenarius", Integer.valueOf(-265));
		realmNameIdMap.put("Zul'jin", Integer.valueOf(-266));
		realmNameIdMap.put("Zuluhed ", Integer.valueOf(-267));
		realmNameIdMap.put("Akama", Integer.valueOf(-268));
		realmNameIdMap.put("Altar of Storms", Integer.valueOf(-269));
		realmNameIdMap.put("Alterac Mountains", Integer.valueOf(-270));
		realmNameIdMap.put("Andorhal", Integer.valueOf(-271));
		realmNameIdMap.put("Anvilmar", Integer.valueOf(-272));
		realmNameIdMap.put("Azgalor", Integer.valueOf(-273));
		realmNameIdMap.put("Azralon", Integer.valueOf(-274));
		realmNameIdMap.put("Barthilas", Integer.valueOf(-275));
		realmNameIdMap.put("Black Dragonflight", Integer.valueOf(-276));
		realmNameIdMap.put("Blackwater Raiders", Integer.valueOf(-277));
		realmNameIdMap.put("Blackwing Lair", Integer.valueOf(-278));
		realmNameIdMap.put("Bleeding Hollow", Integer.valueOf(-279));
		realmNameIdMap.put("Blood Furnace", Integer.valueOf(-280));
		realmNameIdMap.put("Bonechewer", Integer.valueOf(-281));
		realmNameIdMap.put("Burning Legion", Integer.valueOf(-282));
		realmNameIdMap.put("Caelestrasz", Integer.valueOf(-283));
		realmNameIdMap.put("Cairne", Integer.valueOf(-284));
		realmNameIdMap.put("Cenarion Circle", Integer.valueOf(-285));
		realmNameIdMap.put("Cenarius", Integer.valueOf(-286));
		realmNameIdMap.put("Coilfang", Integer.valueOf(-287));
		realmNameIdMap.put("Dark Iron", Integer.valueOf(-288));
		realmNameIdMap.put("Darrowmere", Integer.valueOf(-289));
		realmNameIdMap.put("Dath'Remar", Integer.valueOf(-290));
		realmNameIdMap.put("Dawnbringer", Integer.valueOf(-291));
		realmNameIdMap.put("Demon Soul", Integer.valueOf(-292));
		realmNameIdMap.put("Detheroc", Integer.valueOf(-293));
		realmNameIdMap.put("Drak'Tharon", Integer.valueOf(-294));
		realmNameIdMap.put("Draka", Integer.valueOf(-295));
		realmNameIdMap.put("Drakkari", Integer.valueOf(-296));
		realmNameIdMap.put("Dreadmaul", Integer.valueOf(-297));
		realmNameIdMap.put("Drenden", Integer.valueOf(-298));
		realmNameIdMap.put("Duskwood", Integer.valueOf(-299));
		realmNameIdMap.put("Echo Isles", Integer.valueOf(-300));
		realmNameIdMap.put("Farstriders", Integer.valueOf(-301));
		realmNameIdMap.put("Feathermoon", Integer.valueOf(-302));
		realmNameIdMap.put("Fenris", Integer.valueOf(-303));
		realmNameIdMap.put("Firetree", Integer.valueOf(-304));
		realmNameIdMap.put("Fizzcrank", Integer.valueOf(-305));
		realmNameIdMap.put("Gallywix", Integer.valueOf(-306));
		realmNameIdMap.put("Garithos", Integer.valueOf(-307));
		realmNameIdMap.put("Gnomeregan", Integer.valueOf(-308));
		realmNameIdMap.put("Gorefiend", Integer.valueOf(-309));
		realmNameIdMap.put("Grizzly Hills", Integer.valueOf(-310));
		realmNameIdMap.put("Gundrak", Integer.valueOf(-311));
		realmNameIdMap.put("Gurubashi", Integer.valueOf(-312));
		realmNameIdMap.put("Hydraxis", Integer.valueOf(-313));
		realmNameIdMap.put("Icecrown", Integer.valueOf(-314));
		realmNameIdMap.put("Jubei'Thos", Integer.valueOf(-315));
		realmNameIdMap.put("Kalecgos", Integer.valueOf(-316));
		realmNameIdMap.put("Korgath", Integer.valueOf(-317));
		realmNameIdMap.put("Korialstrasz", Integer.valueOf(-318));
		realmNameIdMap.put("Lethon", Integer.valueOf(-319));
		realmNameIdMap.put("Lightninghoof", Integer.valueOf(-320));
		realmNameIdMap.put("Llane", Integer.valueOf(-321));
		realmNameIdMap.put("Madoran", Integer.valueOf(-322));
		realmNameIdMap.put("Maelstrom", Integer.valueOf(-323));
		realmNameIdMap.put("Maiev", Integer.valueOf(-324));
		realmNameIdMap.put("Misha", Integer.valueOf(-325));
		realmNameIdMap.put("Mok'Nathal", Integer.valueOf(-326));
		realmNameIdMap.put("Moon Guard", Integer.valueOf(-327));
		realmNameIdMap.put("Moonrunner", Integer.valueOf(-328));
		realmNameIdMap.put("Muradin", Integer.valueOf(-329));
		realmNameIdMap.put("Nazgrel", Integer.valueOf(-330));
		realmNameIdMap.put("Nesingwary", Integer.valueOf(-331));
		realmNameIdMap.put("Quel'dorei", Integer.valueOf(-332));
		realmNameIdMap.put("Rivendare", Integer.valueOf(-333));
		realmNameIdMap.put("Scarlet Crusade", Integer.valueOf(-334));
		realmNameIdMap.put("Scilla", Integer.valueOf(-335));
		realmNameIdMap.put("Sentinels", Integer.valueOf(-336));
		realmNameIdMap.put("Shadow Council", Integer.valueOf(-337));
		realmNameIdMap.put("Shadowmoon", Integer.valueOf(-338));
		realmNameIdMap.put("Shandris", Integer.valueOf(-339));
		realmNameIdMap.put("Shu'halo", Integer.valueOf(-340));
		realmNameIdMap.put("Silver Hand", Integer.valueOf(-341));
		realmNameIdMap.put("Sisters of Elune", Integer.valueOf(-342));
		realmNameIdMap.put("Skywall", Integer.valueOf(-343));
		realmNameIdMap.put("Smolderthorn", Integer.valueOf(-344));
		realmNameIdMap.put("Spirestone", Integer.valueOf(-345));
		realmNameIdMap.put("Staghelm", Integer.valueOf(-346));
		realmNameIdMap.put("Stonemaul", Integer.valueOf(-347));
		realmNameIdMap.put("Suramar", Integer.valueOf(-348));
		realmNameIdMap.put("Tanaris", Integer.valueOf(-349));
		realmNameIdMap.put("Thaurissan", Integer.valueOf(-350));
		realmNameIdMap.put("The Forgotten Coast", Integer.valueOf(-351));
		realmNameIdMap.put("The Scryers", Integer.valueOf(-352));
		realmNameIdMap.put("The Underbog", Integer.valueOf(-353));
		realmNameIdMap.put("Thorium Brotherhood", Integer.valueOf(-354));
		realmNameIdMap.put("Thunderlord", Integer.valueOf(-355));
		realmNameIdMap.put("Tol Barad", Integer.valueOf(-356));
		realmNameIdMap.put("Tortheldrin", Integer.valueOf(-357));
		realmNameIdMap.put("Undermine", Integer.valueOf(-358));
		realmNameIdMap.put("Ursin", Integer.valueOf(-359));
		realmNameIdMap.put("Uther", Integer.valueOf(-360));
		realmNameIdMap.put("Velen", Integer.valueOf(-361));
		realmNameIdMap.put("Warsong", Integer.valueOf(-362));
		realmNameIdMap.put("Whisperwind", Integer.valueOf(-363));
		realmNameIdMap.put("Windrunner", Integer.valueOf(-364));
		realmNameIdMap.put("Winterhoof", Integer.valueOf(-365));
		realmNameIdMap.put("Wyrmrest Accord", Integer.valueOf(-366));
		realmNameIdMap.put("Zangarmarsh", Integer.valueOf(-367));


	}
	
	
	public Realm(String name, RegionSelection regionSelection) {
		this.name = name;
		this.regionSelection = regionSelection;
	}

	public RegionSelection getRegionSelection() {
		return regionSelection;
	}

	public String getName() {
		return name;
	}
	
}
